# Generated by Django 4.2.3 on 2023-07-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0002_rename_parking_spot_reserveparkingspot_parkingspot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=200),
        ),
        migrations.AlterField(
            model_name='reserveparkingspot',
            name='status',
            field=models.CharField(default='RESERVED', max_length=200),
        ),
    ]
