# Generated by Django 4.2.3 on 2023-07-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0003_spot_status_alter_reserveparkingspot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
