# Generated by Django 4.2.3 on 2023-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0006_alter_spot_latitude_alter_spot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
