# Generated by Django 4.2.3 on 2023-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0008_alter_spot_latitude_alter_spot_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveparkingspot',
            name='price',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='price',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
