# Generated by Django 4.2.3 on 2023-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0009_reserveparkingspot_price_spot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=38),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=38),
        ),
    ]
