# Generated by Django 4.2.3 on 2023-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingSpots', '0010_alter_spot_latitude_alter_spot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.TextField(),
        ),
    ]
